config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.shop.urls', namespace='shop')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from main.shop.apps import ShopConfig
from main.shop.views import main, contact, ShopListView

app_name = ShopConfig.name

urlpatterns = [
                  path("", main, name="main"),

                  path("contact/", contact, name="contact"),

                  path("shop/", ShopListView.as_view(), name="list"),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/shop/models.py
from django.db import models


# Create your models here.
class Shop(models.Model):
    name = models.CharField(max_length=50, verbose_name="Название")
    price = models.IntegerField(verbose_name="Цена")
    image = models.ImageField(verbose_name='Фото')
    description = models.TextField(max_length=550, verbose_name="Описание")

    def __str__(self):
        return f"{self.name} | {self.price} | {self.image}"

    class Meta:
        verbose_name = "Магазин"
        verbose_name_plural = "Магазины"


class Calculation(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)

main/shop/forms.py
from django import forms

from main.shop.models import Shop, Calculation


class LendingForms(forms.ModelForm):
    class Meta:
        model = Shop
        fields = '__all__'


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100,
                           widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': 'Ваше имя'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control mb-2', 'placeholder': 'email'}))
    number = forms.CharField(max_length=12,
                             widget=forms.TextInput(attrs={'class': 'form-control mb-2', 'placeholder': '8-951-*--**'}))
    message = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control mb-2', 'placeholder': 'Дополнительная информация'}))


class CalculationForm(forms.Form):
    service = forms.ModelChoiceField(queryset=Calculation.objects.all())
    quantity = forms.IntegerField()

main/shop/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from main.shop.forms import ContactForm, CalculationForm
from main.shop.models import Shop
from django.views.generic import ListView


# Create your views here.
def main(request):
    shops = Shop.objects.all()

    context = {
        "shops": shops,

    }
    return render(request, "main_list.html", context)

# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             name = form.cleaned_data['name']
#             email = form.cleaned_data['email']
#             number = form.cleaned_data['number']
#             message = form.cleaned_data['message']
#
#             # Отправка письма
#             send_mail(
#                 'Клиент',
#                 f'Имя: {name}\nEmail: {email}\nНомер: {number}\nСообщение: {message}',
#                 "margoonavt@yandex.ru",
#                 ['margoonavt@yandex.ru'],
#                 fail_silently=False,
#             )
#
#             return render(request, "main_list.html")
#
#     else:
#         form = ContactForm()
#
#     return render(request, 'front/contact.html', {'form': form})

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = request.POST.get('name')
            email = request.POST.get('email')
            number = request.POST.get('number')
            message = request.POST.get('message')

            # Отправка письма
            send_mail(
                'Клиент',
                f'Имя: {name}\nEmail: {email}\nНомер: {number}\nСообщение: {message}',
                "margoonavt@yandex.ru",
                ['margoonavt@yandex.ru'],
                fail_silently=False,
            )

            return render(request, "main_list.html")

    else:
        form = ContactForm()

    return render(request, 'front/contact.html', {'form': form})



# def calculate_cost(request):  #калькулятор
#     if request.method == 'POST':
#         form = CalculationForm(request.POST)
#         if form.is_valid():
#             service = form.cleaned_data['service']
#             quantity = form.cleaned_data['quantity']
#             total_cost = service.price * quantity
#             return render(request, 'front/main_calculation.html', {'form': form, 'total_cost': total_cost})
#     else:
#         form = CalculationForm()
#     return render(request, 'front/main_calculation.html', {'form': form})


class ShopListView(ListView):
    model = Shop
    template_name = "front/shop_list.html"

main/shop/templates/base.html
{% load static %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="{% static 'js/bootstrap.bundle.min.js' %}"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>


<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>


{% include "includes/inc_main_menu.html" %}
{% include "includes/style.html" %}


{% block content %}
{% endblock %}
<footer class="footer" style="background-color: #f9ca24;border-top: 10px solid black">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 wow animate__animated animate__bounceInLeft   ">
                <div class="f_widget company_widget wow fadeInLeft" data-wow-delay="0.2s"
                     style="visibility: visible; animation-delay: 0.2s; animation-name: fadeInLeft;">
                    <h3 class="f-title f_600 t_color f_size_18">Подпишитесь на нашу рассылку </h3>
                    <form action="#" class="f_subscribe_two mailchimp" method="post" novalidate="true"
                          _lpchecked="1">
                        <input type="text" name="EMAIL" class="form-control memail" placeholder="Email">
                        <br>
                        <a>
                            <button class="btn btn-danger rounded-pill px-3" type="button">Подписаться</button>
                        </a>
                        <p class="mchimp-errmessage" style="display: none;"></p>
                        <p class="mchimp-sucmessage" style="display: none;"></p>
                    </form>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow animate__animated animate__bounceInLeft ">
                <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.4s"
                     style="visibility: visible; animation-delay: 0.4s; animation-name: fadeInLeft;">
                    <h3 class="f-title f_600 t_color f_size_18">Телефон
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-telephone-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                  d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
                        </svg>
                    </h3>
                    <h3>8-951-873-22-79</h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow animate__animated animate__bounceInRight">
                <div class="f_widget about-widget pl_70 wow fadeInLeft" data-wow-delay="0.6s"
                     style="visibility: visible; animation-delay: 0.6s; animation-name: fadeInLeft;">
                    <h3 class="f-title f_600 t_color f_size_20">Адрес</h3>
                    <h3>Г.Россошь Пл.танкистов</h3>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 wow animate__animated animate__bounceInRight">
                <div class="f_widget social-widget pl_70 wow fadeInLeft" data-wow-delay="0.8s"
                     style="visibility: visible; animation-delay: 0.8s; animation-name: fadeInLeft;">
                    <h3 class="f-title f_600 t_color f_size_18">Мы в соц.сетях</h3>
                    <div class="f_social_icon">
                        <a href="https://vk.com/s_k_y_s_t_i" target="_blank"><img src="/media/icon/vk.png"
                                                                                  width="40"
                                                                                  height="40"
                                                                                  alt="Вконтакте"></a>

                        <a href="https://t.me/fl1yp" target="_blank"><img
                                src="/media/icon/tg.png"
                                width="40"
                                height="45"
                                alt="40"></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer_bg">
        <div class="footer_bg_one"></div>
        <div class="footer_bg_two"></div>
    </div>
    </div>
    <div class="footer_bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-sm-7">
                    <h2>© 2023 stroy_form.ru</h2>
                </div>
                <div class="col-lg-6 col-sm-5 text-right">
                    <h2>Строительная компания в  Г.Россошь</h2>
                </div>
            </div>
        </div>
    </div>
</footer>
</div>
<script src="/static/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

main/shop/templates/front/advantages.html
<style>

    .or_bg {
        background-color: #f9ca24;
        border-radius: 25%;
        height: 50%;
        text-align: center;
        border: 5px solid black;
        padding: 0 10%;
        margin: 20px;

    }

    .crug {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
    }

    .flex-container {
        display: flex;
        justify-content: center;
    }

    .flex-item {
        flex: 1;
        max-width: 100%; /* Указываем максимальную ширину для адаптивности */
        margin: 0 7%;
    }

    @media (max-width: 1440px ) {
        .or_bg {
            width: 100%;
            margin: 15px;
        }

        .flex-item {
            flex: 1;
            max-width: 100%; /* Указываем максимальную ширину для адаптивности */
            margin: 0 3%;
        }

    }

    @media (max-width: 1024px) {
        .or_bg {
            height: 50%;
        }

        .flex-container {
            align-items: flex-start; /* Добавляем это свойство */
        }

        .card {
            width: 90%; /* Добавляем это свойство */
        }
    }

    @media (max-width: 900px) {
        .or_bg {
            height: 50%;
        }

        .flex-container {
            flex-direction: column;
            align-items: flex-start; /* Центрируем элементы по горизонтали */
        }

        .flex-item {
            width: 90%; /* Устанавливаем ширину 90% */
            margin: 10px 0; /* Добавляем отступы между карточками */
        }
    }

    @media (max-width: 768px) {
        .or_bg {
            height: 50%;
        }

        .flex-container {
            flex-direction: column;
            align-items: flex-start; /* Центрируем элементы по горизонтали */
        }

        .flex-item {
            width: 90%; /* Устанавливаем ширину 90% */
            margin: 10px 0; /* Добавляем отступы между карточками */
        }
    }

</style>
<div class="flex-container">
    <div class="flex-item card" style="border: white">
        <div class="or_bg">
            <img src="/media/icon/free-icon-paint-swatch-3515445.png" alt="" style="width: 50%;">
            <h1>Производство</h1>
            <p style="font-size: 200%">После выезда к вам, ваши замеры передаются в производство и уже в этот же
                день
                полотно будет изготовлено.
                Назначается дата монтажа</p>
        </div>
    </div>
    <div class="flex-item card" style="border: white">
        <div class="or_bg">
            <div class="crug">
                <img src="/media/icon/free-icon-production-2640872.png" alt="" style="width: 50%;">
                <h1>Производство</h1>
                <p style="font-size: 200%">После выезда к вам, ваши замеры передаются в производство и уже в этот же
                    день
                    полотно будет изготовлено.
                    Назначается дата монтажа</p>
            </div>
        </div>
    </div>
    <div class="flex-item card" style="border: white">
        <div class="or_bg">
            <img src="/media/icon/free-icon-paint-swatch-3515445.png" alt="" style="width: 50%;">
            <h1>Производство</h1>
            <p style="font-size: 200%">После выезда к вам, ваши замеры передаются в производство и уже в этот же
                день
                полотно будет изготовлено.
                Назначается дата монтажа</p>
        </div>
    </div>
</div>


<script>
    document.querySelectorAll('.or_bg').forEach(card => {
        card.addEventListener('click', () => {
            openModal();
        });
    });
</script>

main/shop/templates/front/call.html
<style>
    .call {
        position: relative;
    }

    .call-background {
        height: 80%;
        background-size: cover;
        background-attachment: fixed;
        background-image: url("/media/background/img_8.png");
        border: 10px solid black;
    }

    .call-overlay {
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.4); /* Цвет затемнения */
    }

    .calls form {
        border-radius: 40px;
        border: 1px solid #fff; /* Добавьте границу белого цвета */
        color: #fff; /* Измените цвет текста на белый */
        background-color: rgba(0, 0, 0, 0.5);
        opacity: 0.9;
        position: relative;
        z-index: 2;
    }

</style>


<div class="call">
    <div class="call-background">
        <div class="call-overlay">
            <div class="container" style=" margin-top: 10%">
                <h1 style="text-align: center;color: white">Свяжитесь с нами заполнив форму</h1>
                <div class="row" style="margin-top:10%">
                    <div class="col-md-6">
                        <div class="text-center">
                            <h2 style="color: white">Строительная группа Нархозстрой сотрудничает с риэлторскими и
                                девелоперскими
                                компаниями
                                по
                                реализации
                                проектирования, производства и строительства индивидуальной малоэтажной и
                                коммерческой
                                недвижимости.<br>Мы
                                приглашаем застройщиков и дилеров к сотрудничеству.</h2>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="calls">
                            <form class="p-1 p-md-5 border rounded-7 text-end" method="post">
                                {% csrf_token %}
                                <a href="{% url "shop:contact" %}"
                                   class="btn btn-danger form-control">Перейти</a>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

main/shop/templates/front/category.html
<style>
    .cart {
        background-image: url("/media/background/img_13.png");
        background-size: cover;
        background-attachment: fixed;
        width: 100%;
        height: 40%;
        border: 4px solid black;
    }

    .cc {
        display: flex;
        flex-wrap: wrap;
    }

    .cc .card {
        position: relative;
        box-sizing: border-box;
        text-align: center;
        max-width: 25%;
        max-height: 100%;
        padding: 1rem;
        background: #fff;
        box-shadow: 0 5px 15px rgba(0, 0, 0, .1);
        border-radius: 5px;
        margin: 1vw;
        overflow: hidden;
        display: inline-block;
        border: 4px solid black;
    }


    .cc .circle {
        position: relative;
        margin: 0 auto;
        display: flex;
        align-items: center;
        justify-content: center;
        background: #000;
        color: #fff;
        width: 100px;
        height: 100px;
        border-radius: 50%;
        font-size: 2rem;
        font-weight: 700;
        transition: .5s;
    }


    .cc .card .c-3 {
        background: #f9ca24;
        box-shadow: 0 0 0 0;
    }


    .cc .card:hover .c-3 {
        box-shadow: 0 0 0 300px #f9ca24;
    }

    .cc .card .info {
        position: relative;
        z-index: 1;
        transition: .5s;

    }
</style>
<div class="cart">
    <div class="container">
        <div class="cc">
            <div class=" wow animate__animated animate__bounceInUp">
                <div class="card">
                    <div class="circle c-3">
                        <img src="/media/icon/free-icon-production-2640872.png" style="width: 100%;height: 100%">
                    </div>
                    <div class="info">
                        <h3>Card hover effects</h3>
                        <p>Card design with hover effect by using pure CSS</p>
                    </div>
                </div>
                <div class="card">
                    <div class="circle c-3">
                        <img src="/media/icon/free-icon-paint-swatch-3515445.png" style="width: 100%;height: 100%">
                    </div>
                    <div class="info">
                        <h3>Card hover effects</h3>
                        <p>Card design with hover effect by using pure CSS</p>
                    </div>
                </div>
                <div class="card">
                    <div class="circle c-3">
                        <img src="/media/icon/free-icon-tools-1505634.png" style="width: 100%;height: 100%">
                    </div>
                    <div class="info">
                        <h3>Card hover effects</h3>
                        <p>Card design with hover effect by using pure CSS</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

main/shop/templates/front/contact.html
{% extends "base.html" %}
{% block content %}

    <style>
        .call {
            position: relative;
        }

        .call-background {
            height: 80%;
            background-size: cover;
            background-attachment: fixed;
            background-image: url("/media/background/img_8.png");
            border: 10px solid black;
        }

        .call-overlay {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.4); /* Цвет затемнения */
        }

        .calls form {
            border-radius: 40px;
            border: 1px solid #fff; /* Добавьте границу белого цвета */
            color: #fff; /* Измените цвет текста на белый */
            background-color: rgba(0, 0, 0, 0.5);
            opacity: 0.9;
            position: relative;
            z-index: 2;
        }

        /* Стили для мобильных устройств */
        @media (max-width: 767px) {
            .calls form {
                margin-top: 50px; /* Измените отступ сверху для формы */
            }
        }

    </style>

    <div class="call">
        <div class="call-background">
            <div class="call-overlay">
                <div class="container" style=" margin-top: 4%">
                    <h1 style="text-align: center;color: white">Свяжитесь с нами заполнив форму</h1>
                    <div class="row" style="margin-top:10%">
                        <div class="col-md-6">
                            <div class="text-center">
                                <h2 style="color: white">Строительная группа Нархозстрой сотрудничает с риэлторскими и
                                    девелоперскими
                                    компаниями
                                    по
                                    реализации
                                    проектирования, производства и строительства индивидуальной малоэтажной и
                                    коммерческой
                                    недвижимости.<br>Мы
                                    приглашаем застройщиков и дилеров к сотрудничеству.</h2>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="calls">
                                <form class="p-1 p-md-5 border rounded-7 text-sm-start" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <label for="id_name">Имя:</label>
                                        {{ form.name }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_email">Email:</label>
                                        {{ form.email }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_number">Номер телефона:</label>
                                        {{ form.number }}
                                    </div>
                                    <div class="form-group">
                                        <label for="id_message">Сообщение:</label>
                                        {{ form.message }}
                                    </div>
                                    <button type="submit" class="btn btn-danger form-control">Отправить</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
    </div>






    <script type="text/javascript" charset="utf-8" async
            src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A6300d4806ac23516c790a7a9b838e82d01a6190f7d73010293188b7a132537a8&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;scroll=true"></script>

{% endblock %}

main/shop/templates/front/main_calculation.html
<style>
    .callс {
        position: relative;
        height: 50%;
        background-size: cover;
        background-attachment: fixed;
        text-align: center; /* Центрируем элементы */
        background-image: url("/media/background/img_17.png");
        display: flex;
        justify-content: center;
        align-items: center;
        padding: 10% 0 10% 20%; /* top, right, bottom, left padding */
        border: 10px solid black;
    }

    .callс::before {
        content: "";
        position: absolute;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.4); /* Цвет затемнения */
    }

    .callс .calls form {
        border-radius: 40px;
        border: 1px solid #fff; /* Добавьте границу белого цвета */
        color: #fff; /* Измените цвет текста на белый */
        background-color: rgba(0, 0, 0, 0.5);
        opacity: 0.9;
        padding: 20px; /* Добавьте отступы */
        width: 50%; /* Занимайте всю доступную ширину */
    }

    @media (max-width: 768px) {
        .callс {
            padding: 10% 10% 10% 10%;
            width: 150% /* Измените отступы для мобильных устройств */
        }
    }


    h1 {
        position: relative;
        z-index: 1;
        text-align: center; /* Центрируем текст */
    }

    .calls {
        position: relative;
        z-index: 2; /* Убедитесь, что форма отображается над заголовком */
    }

</style>
<h1 class="text-black">Здесь вы можете посчитать общую квадратуру</h1>

<div class="callс">
    <div class="container">
        <div class="py-5 text-center">

            <div class="calls">
                <form id="areaCalculatorForm" class="p-1 p-md-5 border rounded-7" method="post">
                    <h4 class="my-10 fw-normal">Калькулятор площади м2</h4>
                    <div class="card-body" style="margin:4px">
                        <div>
                            <label for="length">Длинна:</label>
                            <input class="form-control mb-2" type="number" id="length" name="length" required>
                            <label for="width">Ширина:</label>
                            <input class="form-control mb-2" type="number" id="width" name="width" required>
                            <label for="sum_metr">Цена за метр:</label>
                            <input class="form-control mb-2" type="number" id="sum_metr" name="sum_metr" required>
                        </div>
                        <br>
                        <input type="submit" value="Посчитать" class="w-50 btn btn-lg btn-primary">
                    </div>
                    <div id="result"></div>
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    document.getElementById('areaCalculatorForm').addEventListener('submit', function (e) {
        e.preventDefault(); // Предотвращает перезагрузку страницы
        var length = parseInt(document.getElementById('length').value);
        var width = parseInt(document.getElementById('width').value);
        var one_metr = parseInt(document.getElementById('sum_metr').value);
        var area = length * width;
        var sum = area * one_metr;

        document.getElementById('result').innerHTML = '<h2>Общая площадь: ' + area + ' м2<br> Общая цена: ' + sum + '</h2>';
    });
</script>

main/shop/templates/front/offers.html
<h1 style="margin-top: 10%;margin-bottom: 10%;text-align: center;font-size: 100px">Почему мы?</h1>
<div class="container marketing">
    <hr class="featurette-divider">
    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">First featurette heading. <span
                    class="text-body-secondary">1</span>
            </h2>
            <p class="lead">Первый +</p>
        </div>
        <div class="col-md-5  wow animate__animated animate__bounceInRight">
            <img src="/media/background/img_3.png" style="border:2px solid black; width: 100%;height: 100%"></div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7 order-md-2">
            <h2 class="featurette-heading fw-normal lh-1">2<span
                    class="text-body-secondary">See for yourself.</span>
            </h2>
            <p class="lead">Второй +</p>
        </div>
        <div class="col-md-5 order-md-1  wow animate__animated animate__bounceInLeft">
            <img src="/media/background/img_3.png" style=" border:2px solid black;  width: 100%;height: 100%"></div>
    </div>

    <hr class="featurette-divider">

    <div class="row featurette">
        <div class="col-md-7">
            <h2 class="featurette-heading fw-normal lh-1">And lastly, this one. <span
                    class="text-body-secondary">3</span>
            </h2>
            <p class="lead">Третий +</p>
        </div>
        <div class="col-md-5 wow animate__animated animate__bounceInRight">
            <img src="/media/background/img_3.png" style="border:2px solid black;  width: 100%;height: 100%"></div>
    </div>
</div><!-- /.container -->

main/shop/templates/front/shop.html
<style>
    .ups {
        margin-top: 10%;
    }

    .card {
        position: relative;
        transition: transform 0.3s;
    }

    .card:hover {
        transform: scale(1.05);
        z-index: 1;
    }

    .btn-outline-primary {
        color: black;
        border-color: #ffcd39;
    }

    .btn-outline-primary:hover {
        background-color: #ffcd39;
        color: black; /* Цвет текста кнопки при наведении */
    }
</style>


{% load mediapath %}
<h1 style="margin-top: 15%;margin-bottom: 15%;text-align: center;font-size: 100px">Наше производство</h1>
<div class="ups">
    <div class="row row-cols-3 mb-3 text-center">
        {% for shop in shops %}
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-body">
                        <img src="{% mediapath shop.image %}" width="75%" height="75%" alt="Иллюстрация">
                        <ul class="list-unstyled mt-3 mb-4">
                            <h3 class="card-text">{{ shop.name|title|truncatechars:100 }}</h3>
                        </ul>
                        <button type="button" class="w-100 btn btn-lg btn-outline-primary">
                            Подробнее
                        </button>
                    </div>
                </div>
            </div>
            <script>
                document.querySelectorAll('.card').forEach(card => {
                    card.addEventListener('click', () => {
                        openModal();
                    });
                });

            </script>
        {% endfor %}
    </div>
</div>

main/shop/templates/includes/inc_main_menu.html
    <style>
        .up_menu{
            background-color: grey;
            width: 100%;
            height: 2%;
        }
    </style>
<header data-bs-theme="dark">
<div class="up_menu">
 <p style="color: #ffcd39; text-align: right;margin-right: 20%;word-spacing: 30px;">+7-951-888-99-99 swar@gmail.com</p>
</div>
    <nav class="menu menu-1">
        <ul>
            <li><a href="{% url "shop:main" %}">ГЛАВНАЯ</a></li>
            <li><a href="{% url "shop:list" %}">МАГАЗИН</a></li>
            <li><a href="{% url "shop:contact" %}">КОНТАКТЫ</a></li>
        </ul>
    </nav>
</header>